version: '3'
services:
  front:
    build: ./front
    ports:
      - '3000:3000'
    depends_on:
      - server
      - carFactoryDB
    volumes:
      - ./front/src:/app/src
  server:
    build: ./server
    ports:
      - '9001:9001'
    depends_on:
      - carFactoryDB
    volumes:
      - ./server:/app
  carFactoryDB:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=carFactoryDB
    ports:
      - "5432:5432" 
    volumes: 
      - ./data/database-data:/var/lib/postgresql/data/
